from __future__ import annotations

import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.paths import find_backend_root
from app.schemas.cloudops_autopilot import (
    CloudOpsArtifactStatus,
    CloudOpsAzureResource,
    CloudOpsAzureSnapshot,
    CloudOpsDeploymentPlan,
    CloudOpsGeneratedApp,
    CloudOpsOverviewResponse,
    CloudOpsPlanStep,
    CloudOpsToolStatus,
)


class CloudOpsAutopilotService:
    """Read-only operations console for apps generated by AI Cloud App Factory."""

    ARTIFACTS = [
        (
            "backend",
            "Backend FastAPI",
            "backend/app/main.py",
            "API, OpenAPI docs and health endpoint.",
        ),
        (
            "frontend",
            "Frontend React",
            "frontend/src/App.tsx",
            "User interface built by the app factory.",
        ),
        (
            "compose",
            "Docker Compose",
            "docker-compose.yml",
            "Local runtime with frontend, API and PostgreSQL.",
        ),
        (
            "terraform",
            "Terraform Azure",
            "infra/terraform/main.tf",
            "Infrastructure definition for Azure resources.",
        ),
        (
            "workflow",
            "GitHub Actions",
            ".github/workflows/deploy-azure-container-apps.yml",
            "CI/CD workflow for Azure Container Apps.",
        ),
        (
            "deploy_script",
            "Deploy script",
            "scripts/deploy-azure.ps1",
            "Manual deploy path from this machine.",
        ),
    ]

    def __init__(self) -> None:
        self.backend_root = find_backend_root()
        self.project_root = self.backend_root.parent
        self.generated_root = self.project_root / "generated-apps"

    def overview(self, app_id: str | None = None) -> CloudOpsOverviewResponse:
        apps = self.list_generated_apps()
        selected_app = self._select_app(apps, app_id)
        azure = self.azure_snapshot()
        return CloudOpsOverviewResponse(
            title="CloudOps Autopilot Azure",
            mode="operations-console",
            generated_root=str(self.generated_root),
            tools=self.tool_status(),
            apps=apps,
            selected_app=selected_app,
            azure=azure,
            plan=self.plan(selected_app, azure),
        )

    def list_generated_apps(self) -> list[CloudOpsGeneratedApp]:
        if not self.generated_root.exists():
            return []

        apps: list[CloudOpsGeneratedApp] = []
        for path in sorted(self.generated_root.iterdir(), key=lambda item: item.stat().st_mtime, reverse=True):
            if path.is_dir():
                apps.append(self._inspect_generated_app(path))
        return apps

    def tool_status(self) -> list[CloudOpsToolStatus]:
        tools = [
            ("git", "Version control for local commits and remote push."),
            ("docker", "Builds frontend and backend container images."),
            ("terraform", "Applies Azure infrastructure templates."),
            ("az", "Reads and deploys Azure resources from this machine."),
            ("gh", "Optional GitHub CLI for auth and repository operations."),
        ]
        statuses = [self._tool_status(command, detail) for command, detail in tools]
        statuses.append(self._azure_auth_status())
        return statuses

    def azure_snapshot(self) -> CloudOpsAzureSnapshot:
        if shutil.which("az") is None:
            return CloudOpsAzureSnapshot(authenticated=False, errors=["Azure CLI is not installed."])

        account, account_error = self._az_json(
            ["az", "account", "show", "--query", "{name:name,id:id,tenantId:tenantId,user:user.name}", "-o", "json"],
            timeout=30,
        )
        if account_error:
            return CloudOpsAzureSnapshot(authenticated=False, errors=[account_error])

        resource_groups, rg_error = self._az_json(
            ["az", "group", "list", "--query", "[].{name:name,location:location}", "-o", "json"],
            timeout=40,
        )
        container_apps, ca_error = self._az_json(
            [
                "az",
                "containerapp",
                "list",
                "--query",
                "[].{name:name,resourceGroup:resourceGroup,location:location,status:properties.provisioningState,url:properties.configuration.ingress.fqdn}",
                "-o",
                "json",
            ],
            timeout=60,
        )
        registries, acr_error = self._az_json(
            ["az", "acr", "list", "--query", "[].{name:name,resourceGroup:resourceGroup,location:location,url:loginServer}", "-o", "json"],
            timeout=45,
        )
        postgres_servers, pg_error = self._az_json(
            [
                "az",
                "postgres",
                "flexible-server",
                "list",
                "--query",
                "[].{name:name,resourceGroup:resourceGroup,location:location,status:state,url:fullyQualifiedDomainName}",
                "-o",
                "json",
            ],
            timeout=60,
        )

        errors = [error for error in [rg_error, ca_error, acr_error, pg_error] if error]
        return CloudOpsAzureSnapshot(
            authenticated=True,
            subscription_name=str(account.get("name") or ""),
            subscription_id=str(account.get("id") or ""),
            tenant_id=str(account.get("tenantId") or ""),
            user=str(account.get("user") or ""),
            resource_groups=self._resources(resource_groups, "Resource Group"),
            container_apps=self._resources(container_apps, "Container App"),
            registries=self._resources(registries, "Container Registry"),
            postgres_servers=self._resources(postgres_servers, "PostgreSQL Flexible Server"),
            errors=errors,
        )

    def plan(self, app: CloudOpsGeneratedApp | None, azure: CloudOpsAzureSnapshot | None = None) -> CloudOpsDeploymentPlan:
        azure = azure or self.azure_snapshot()
        if app is None:
            return CloudOpsDeploymentPlan(
                app_id=None,
                app_slug=None,
                project_path=None,
                mode="readiness",
                summary="No generated app is selected yet.",
                readiness_score=0,
                required_inputs=["Generate an app in Application 04 or select an existing generated app."],
                steps=[
                    CloudOpsPlanStep(
                        name="Select generated app",
                        stage="validate",
                        status="blocked",
                        detail="CloudOps needs a project folder with backend, frontend, Docker, Terraform and deploy script.",
                    )
                ],
                matched_azure_resources=[],
            )

        required_inputs = self._required_inputs(app, azure)
        matched_resources = self._matched_resources(app.slug, azure)
        steps = self._plan_steps(app, azure, matched_resources)
        status_word = "ready" if app.readiness_score >= 90 and azure.authenticated else "needs configuration"
        return CloudOpsDeploymentPlan(
            app_id=app.id,
            app_slug=app.slug,
            project_path=app.path,
            mode="cloudops-mvp",
            summary=(
                f"{app.name} is {status_word}: CloudOps can validate the project, reuse Azure environment, "
                "build images, deploy Container Apps and turn on observability."
            ),
            readiness_score=app.readiness_score,
            required_inputs=required_inputs,
            steps=steps,
            matched_azure_resources=matched_resources,
        )

    def _inspect_generated_app(self, path: Path) -> CloudOpsGeneratedApp:
        artifacts = [
            CloudOpsArtifactStatus(
                key=key,
                label=label,
                path=relative,
                present=(path / relative).exists(),
                purpose=purpose,
            )
            for key, label, relative, purpose in self.ARTIFACTS
        ]
        present = sum(1 for artifact in artifacts if artifact.present)
        readiness_score = round((present / len(artifacts)) * 100)
        if readiness_score >= 90:
            status = "ready"
        elif readiness_score >= 50:
            status = "partial"
        else:
            status = "blocked"

        readme = self._read_text(path / "README.md")
        stat = path.stat()
        return CloudOpsGeneratedApp(
            id=path.name,
            name=self._project_name(path, readme),
            slug=self._slug_from_dir(path.name),
            path=str(path),
            created_at=self._timestamp_to_datetime(stat.st_ctime),
            updated_at=self._timestamp_to_datetime(stat.st_mtime),
            status=status,
            readiness_score=readiness_score,
            artifacts=artifacts,
            azure_links=self._extract_azure_links(readme),
            github_url=self._extract_github_url(readme),
        )

    def _select_app(self, apps: list[CloudOpsGeneratedApp], app_id: str | None) -> CloudOpsGeneratedApp | None:
        if not apps:
            return None
        if app_id:
            for app in apps:
                if app.id == app_id:
                    return app
        return apps[0]

    def _tool_status(self, command: str, detail: str) -> CloudOpsToolStatus:
        available = shutil.which(command) is not None
        return CloudOpsToolStatus(
            name=command,
            available=available,
            detail=f"{detail} {'Available.' if available else 'Missing.'}",
        )

    def _azure_auth_status(self) -> CloudOpsToolStatus:
        if shutil.which("az") is None:
            return CloudOpsToolStatus(name="azure-auth", available=False, detail="Azure CLI is missing.")
        payload, error = self._az_json(
            ["az", "account", "show", "--query", "{user:user.name,name:name}", "-o", "json"],
            timeout=30,
        )
        if error:
            return CloudOpsToolStatus(name="azure-auth", available=False, detail="Azure login is not active.")
        return CloudOpsToolStatus(
            name="azure-auth",
            available=True,
            detail=f"Connected as {payload.get('user')} on {payload.get('name')}.",
        )

    def _az_json(self, command: list[str], *, timeout: int) -> tuple[Any, str | None]:
        az_path = shutil.which("az")
        if az_path is None:
            return [], "Azure CLI is not installed."
        command = [az_path, *command[1:]]
        use_shell = az_path.lower().endswith((".cmd", ".bat"))
        try:
            completed = subprocess.run(
                subprocess.list2cmdline(command) if use_shell else command,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
                shell=use_shell,
            )
        except Exception as exc:
            return [], str(exc)
        if completed.returncode != 0:
            return [], self._tail(completed.stderr or completed.stdout)
        try:
            return json.loads(completed.stdout or "[]"), None
        except json.JSONDecodeError:
            return [], "Azure CLI returned invalid JSON."

    def _resources(self, rows: Any, resource_type: str) -> list[CloudOpsAzureResource]:
        if not isinstance(rows, list):
            return []
        resources: list[CloudOpsAzureResource] = []
        for row in rows:
            if not isinstance(row, dict):
                continue
            url = str(row.get("url") or "") or None
            if url and not url.startswith("http") and "." in url:
                url = f"https://{url}"
            resources.append(
                CloudOpsAzureResource(
                    name=str(row.get("name") or ""),
                    resource_group=str(row.get("resourceGroup") or row.get("resource_group") or row.get("name") or ""),
                    type=resource_type,
                    location=str(row.get("location") or "") or None,
                    status=str(row.get("status") or "") or None,
                    url=url,
                )
            )
        return resources

    def _required_inputs(self, app: CloudOpsGeneratedApp, azure: CloudOpsAzureSnapshot) -> list[str]:
        required: list[str] = []
        if not azure.authenticated:
            required.append("Azure CLI login: run az login and select the subscription.")
        if app.readiness_score < 90:
            missing = [artifact.label for artifact in app.artifacts if not artifact.present]
            required.append(f"Regenerate or repair missing artifacts: {', '.join(missing)}.")
        if not any(resource.type == "Container App" for resource in self._matched_resources(app.slug, azure)):
            required.append("First deployment will create or update Azure Container Apps.")
        if not app.github_url:
            required.append("Optional: publish the generated app to GitHub for CI/CD history.")
        return required

    def _plan_steps(
        self,
        app: CloudOpsGeneratedApp,
        azure: CloudOpsAzureSnapshot,
        matched_resources: list[CloudOpsAzureResource],
    ) -> list[CloudOpsPlanStep]:
        has_artifacts = app.readiness_score >= 90
        has_container_app = any(resource.type == "Container App" for resource in matched_resources)
        has_registry = any(resource.type == "Container Registry" for resource in matched_resources)
        has_postgres = any(resource.type == "PostgreSQL Flexible Server" for resource in matched_resources)
        return [
            CloudOpsPlanStep(
                name="Validate factory output",
                stage="validate",
                status="ready" if has_artifacts else "blocked",
                detail="Backend, frontend, Docker, Terraform, workflow and deploy script are present."
                if has_artifacts
                else "Some generated project artifacts are missing.",
            ),
            CloudOpsPlanStep(
                name="Connect Azure subscription",
                stage="validate",
                status="ready" if azure.authenticated else "blocked",
                detail=f"Using subscription {azure.subscription_name}."
                if azure.authenticated
                else "Azure CLI must be authenticated before deploying.",
            ),
            CloudOpsPlanStep(
                name="Provision cloud foundation",
                stage="provision",
                status="ready" if has_registry and has_postgres else "manual",
                detail="ACR/PostgreSQL already found for this app."
                if has_registry and has_postgres
                else "Terraform will create or reuse ACR, PostgreSQL, Key Vault and Container Apps Environment.",
            ),
            CloudOpsPlanStep(
                name="Build and push images",
                stage="build",
                status="manual" if has_artifacts else "blocked",
                detail="Docker builds API and Web images, then pushes them to ACR.",
            ),
            CloudOpsPlanStep(
                name="Release Container Apps",
                stage="release",
                status="ready" if has_container_app else "manual",
                detail="Container Apps already exist and can be updated."
                if has_container_app
                else "First release will create frontend and backend Container Apps.",
            ),
            CloudOpsPlanStep(
                name="Turn on observability",
                stage="observe",
                status="manual",
                detail="Connect Application Insights, Log Analytics, health checks and deployment links.",
            ),
            CloudOpsPlanStep(
                name="Govern cost and cleanup",
                stage="govern",
                status="warning",
                detail="Review failed Container Apps, budgets and unused resource groups before repeated demos.",
            ),
        ]

    def _matched_resources(self, slug: str, azure: CloudOpsAzureSnapshot) -> list[CloudOpsAzureResource]:
        compact = slug.replace("-", "")
        candidates = [
            *azure.resource_groups,
            *azure.container_apps,
            *azure.registries,
            *azure.postgres_servers,
        ]
        matches = []
        for resource in candidates:
            text = f"{resource.name} {resource.resource_group}".lower()
            if slug.lower() in text or compact.lower() in text.replace("-", ""):
                matches.append(resource)
        return matches

    def _read_text(self, path: Path) -> str:
        if not path.exists():
            return ""
        try:
            return path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return path.read_text(encoding="latin-1", errors="ignore")

    def _project_name(self, path: Path, readme: str) -> str:
        for line in readme.splitlines():
            if line.startswith("# "):
                return line.removeprefix("# ").strip()
        return self._slug_from_dir(path.name).replace("-", " ").title()

    def _slug_from_dir(self, name: str) -> str:
        return re.sub(r"-\d{8}-\d{6}$", "", name).strip("-") or name

    def _extract_azure_links(self, readme: str) -> list[str]:
        links: list[str] = []
        for line in readme.splitlines():
            if "Azure:" not in line and "API Azure:" not in line and "API Docs Azure:" not in line:
                continue
            match = re.search(r"https://\S+", line)
            if match:
                links.append(match.group(0).rstrip(").,"))
        return links

    def _extract_github_url(self, readme: str) -> str | None:
        match = re.search(r"https://github\.com/\S+", readme)
        return match.group(0).rstrip(").,") if match else None

    def _timestamp_to_datetime(self, value: float) -> datetime:
        return datetime.fromtimestamp(value, tz=timezone.utc)

    def _tail(self, value: str, max_lines: int = 5) -> str:
        lines = [line.strip() for line in value.splitlines() if line.strip()]
        return "\n".join(lines[-max_lines:]) if lines else "Azure CLI command failed."
