import {
  BarChart3,
  Cloud,
  Database,
  Gauge,
  KeyRound,
  Server,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

import type {
  DatabaseSource,
  ImplementationPhase,
  TableInventoryItem,
  TowerIntegration,
  TowerRecommendation,
} from "./types";

export const databaseSources: DatabaseSource[] = [
  {
    id: "cloudapp_postgres",
    name: "cloudapp_postgres",
    displayName: "CloudApp PostgreSQL",
    sourceType: "docker_database",
    engine: "postgresql",
    environment: "local",
    location: "Local Docker",
    host: "localhost",
    port: 5432,
    databaseName: "cloudapp",
    username: "cloudapp",
    secretRef: "cloudapp-local-password",
    containerName: "cloudapp_postgres",
    cloudProvider: "none",
    telemetryProvider: "Application Insights",
    status: "online",
    healthScore: 94,
    latencyMs: 12,
    activeConnections: 4,
    totalConnections: 9,
    idleConnections: 5,
    databaseSizeMb: 320,
    tablesCount: 38,
    locksCount: 7,
    schemas: ["public"],
    badges: ["Docker", "PostgreSQL", "App Insights"],
    actions: ["Detail", "Tables", "Sessions", "Locks"],
    lastSnapshot: "hace 1 min",
    trend: [89, 90, 92, 93, 94, 94, 95, 94],
  },
  {
    id: "sentinel_postgres",
    name: "sentinel_postgres",
    displayName: "Sentinel Lab PostgreSQL",
    sourceType: "docker_database",
    engine: "postgresql",
    environment: "local",
    location: "Local Docker",
    host: "localhost",
    port: 5433,
    databaseName: "core_banking_sim",
    username: "sentinel",
    secretRef: "sentinel-postgres-password",
    containerName: "sentinel_postgres",
    cloudProvider: "none",
    telemetryProvider: "Application Insights",
    status: "online",
    healthScore: 92,
    latencyMs: 15,
    activeConnections: 2,
    totalConnections: 12,
    idleConnections: 10,
    databaseSizeMb: 180,
    tablesCount: 8,
    locksCount: 4,
    schemas: ["public"],
    badges: ["Docker", "PostgreSQL", "Sentinel"],
    actions: ["Detail", "Tables", "Sessions", "Locks"],
    lastSnapshot: "hace 1 min",
    trend: [86, 88, 90, 91, 93, 92, 91, 92],
  },
  {
    id: "azure_postgres_cloudapp",
    name: "azure_postgres_cloudapp",
    displayName: "Azure PostgreSQL CloudApp",
    sourceType: "cloud_database",
    engine: "postgresql",
    environment: "azure-dev",
    location: "Azure East US",
    host: "psql-cloudapp-dev-zgc5ku4.postgres.database.azure.com",
    port: 5432,
    databaseName: "cloudapp",
    username: "cloudappadmin",
    secretRef: "azure-postgres-cloudapp-password",
    cloudProvider: "azure",
    telemetryProvider: "Azure Monitor",
    status: "degraded",
    healthScore: 87,
    latencyMs: 95,
    activeConnections: 6,
    totalConnections: 14,
    idleConnections: 8,
    databaseSizeMb: 410,
    tablesCount: 38,
    locksCount: 5,
    schemas: ["public"],
    badges: ["Azure", "PostgreSQL", "Azure Monitor", "SSL"],
    actions: ["Cloud Metrics", "Tables", "Recommendations"],
    lastSnapshot: "hace 2 min",
    trend: [91, 90, 89, 88, 88, 87, 86, 87],
  },
  {
    id: "databricks_lakehouse",
    name: "databricks_lakehouse",
    displayName: "Databricks Lakehouse",
    sourceType: "lakehouse",
    engine: "databricks",
    environment: "cloud",
    location: "Azure Databricks",
    host: "SQL Warehouse",
    port: 443,
    databaseName: "banco_demo / tpcds",
    username: "token",
    secretRef: "databricks-token",
    cloudProvider: "azure",
    telemetryProvider: "Databricks",
    status: "online",
    healthScore: 90,
    latencyMs: 145,
    activeConnections: null,
    totalConnections: null,
    idleConnections: null,
    databaseSizeMb: null,
    tablesCount: 9,
    locksCount: null,
    schemas: ["banco_demo", "tpcds_bronze", "tpcds_silver", "tpcds_gold"],
    badges: ["Databricks", "Lakehouse", "Key Vault"],
    actions: ["Schemas", "Tables", "History"],
    lastSnapshot: "hace 4 min",
    trend: [88, 89, 89, 90, 90, 91, 90, 90],
  },
  {
    id: "controltower_postgres",
    name: "controltower_postgres",
    displayName: "Control Tower PostgreSQL",
    sourceType: "system_database",
    engine: "postgresql",
    environment: "local",
    location: "Local Docker",
    host: "localhost",
    port: 5440,
    databaseName: "controltower",
    username: "controltower",
    secretRef: "controltower-postgres-password",
    containerName: "controltower_postgres",
    cloudProvider: "none",
    telemetryProvider: "Application Insights",
    status: "online",
    healthScore: 95,
    latencyMs: 10,
    activeConnections: 1,
    totalConnections: 5,
    idleConnections: 4,
    databaseSizeMb: 64,
    tablesCount: 5,
    locksCount: 2,
    schemas: ["public"],
    badges: ["Docker", "System DB", "Snapshots"],
    actions: ["History", "Snapshots", "Config"],
    lastSnapshot: "pendiente",
    trend: [95, 95, 95, 96, 95, 95, 95, 95],
  },
];

export const tableInventory: TableInventoryItem[] = [
  { sourceId: "cloudapp_postgres", schemaName: "public", tableName: "sentinel_metric_samples", estimatedRows: 7110, sizeMb: 42, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "cloudapp_postgres", schemaName: "public", tableName: "sentinel_incidents", estimatedRows: 5, sizeMb: 3, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "cloudapp_postgres", schemaName: "public", tableName: "catalog_assets", estimatedRows: 24, sizeMb: 5, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "sentinel_postgres", schemaName: "public", tableName: "accounts", estimatedRows: 5000, sizeMb: 28, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "sentinel_postgres", schemaName: "public", tableName: "transactions", estimatedRows: 10000, sizeMb: 55, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "sentinel_postgres", schemaName: "public", tableName: "transfers", estimatedRows: 5000, sizeMb: 24, tableType: "table", lastSeenAt: "2026-05-25 22:30" },
  { sourceId: "azure_postgres_cloudapp", schemaName: "public", tableName: "platform_services", estimatedRows: 3, sizeMb: 2, tableType: "table", lastSeenAt: "2026-05-25 22:20" },
  { sourceId: "azure_postgres_cloudapp", schemaName: "public", tableName: "catalog_columns", estimatedRows: 180, sizeMb: 9, tableType: "table", lastSeenAt: "2026-05-25 22:20" },
  { sourceId: "databricks_lakehouse", schemaName: "banco_demo", tableName: "transacciones_demo", estimatedRows: 250000, sizeMb: 740, tableType: "delta", lastSeenAt: "2026-05-25 22:10" },
  { sourceId: "databricks_lakehouse", schemaName: "banco_demo", tableName: "alertas_movimientos_inusuales", estimatedRows: 1200, sizeMb: 18, tableType: "delta", lastSeenAt: "2026-05-25 22:10" },
  { sourceId: "databricks_lakehouse", schemaName: "tpcds_bronze", tableName: "store_sales", estimatedRows: 420000, sizeMb: 980, tableType: "delta", lastSeenAt: "2026-05-25 22:10" },
  { sourceId: "databricks_lakehouse", schemaName: "tpcds_silver", tableName: "store_sales_clean", estimatedRows: 398000, sizeMb: 840, tableType: "delta", lastSeenAt: "2026-05-25 22:10" },
  { sourceId: "databricks_lakehouse", schemaName: "tpcds_gold", tableName: "sales_by_store", estimatedRows: 2400, sizeMb: 32, tableType: "delta", lastSeenAt: "2026-05-25 22:10" },
  { sourceId: "controltower_postgres", schemaName: "public", tableName: "monitored_sources", estimatedRows: 5, sizeMb: 1, tableType: "table", lastSeenAt: "pendiente" },
  { sourceId: "controltower_postgres", schemaName: "public", tableName: "source_metric_snapshots", estimatedRows: 0, sizeMb: 1, tableType: "table", lastSeenAt: "pendiente" },
];

export const integrations: TowerIntegration[] = [
  {
    id: "key-vault",
    name: "Azure Key Vault",
    provider: "Azure",
    status: "configured",
    signal: "Secret refs definidos",
    description: "Passwords, tokens y connection strings sin exponerlos en React.",
    Icon: KeyRound,
  },
  {
    id: "app-insights",
    name: "Application Insights",
    provider: "Azure",
    status: "configured",
    signal: "Backend telemetry",
    description: "Requests, errores, latencias y health checks desde FastAPI local.",
    Icon: Gauge,
  },
  {
    id: "log-analytics",
    name: "Log Analytics",
    provider: "Azure",
    status: "configured",
    signal: "KQL ready",
    description: "Eventos y trazas consultables desde Application Insights y diagnostic settings.",
    Icon: BarChart3,
  },
  {
    id: "azure-monitor",
    name: "Azure Monitor",
    provider: "Azure",
    status: "configured",
    signal: "Native metrics",
    description: "CPU, storage, I/O, conexiones y alertas de Azure PostgreSQL.",
    Icon: Cloud,
  },
  {
    id: "databricks",
    name: "Databricks SQL Warehouse",
    provider: "Databricks",
    status: "configured",
    signal: "Catalog visibility",
    description: "Catalogos, schemas, tablas Delta y ejecuciones SQL Warehouse.",
    Icon: Sparkles,
  },
  {
    id: "local-docker",
    name: "Local Docker PostgreSQL",
    provider: "Local",
    status: "connected",
    signal: "localhost ports",
    description: "cloudapp_postgres, sentinel_postgres y controltower_postgres.",
    Icon: Server,
  },
];

export const recommendations: TowerRecommendation[] = [
  {
    id: "rec-azure-latency",
    sourceId: "azure_postgres_cloudapp",
    severity: "medium",
    category: "Latency",
    title: "Azure PostgreSQL tiene mayor latencia que las bases locales",
    recommendation: "Revisar region, SSL, red, carga del flexible server y metricas de Azure Monitor.",
    evidence: "95 ms frente a 12-15 ms en Docker local.",
    impact: "Puede afectar operaciones de gobierno, catalogo y Sentinel en modo cloud.",
    actionType: "read_only",
  },
  {
    id: "rec-locks",
    sourceId: "sentinel_postgres",
    severity: "high",
    category: "Locks",
    title: "Locks detectados en base de simulacion bancaria",
    recommendation: "Revisar pg_stat_activity, pg_locks y transacciones largas antes de una demo critica.",
    evidence: "Locks count mayor que cero y workload de transferencias activo.",
    impact: "Puede generar esperas, timeouts o incidentes tipo deadlock.",
    actionType: "approval_required",
  },
  {
    id: "rec-bronze-gold",
    sourceId: "databricks_lakehouse",
    severity: "low",
    category: "Lakehouse",
    title: "Bronze y Silver tienen mas volumen que Gold",
    recommendation: "Agregar agregados Gold adicionales para dashboards ejecutivos y consumo BI.",
    evidence: "store_sales y store_sales_clean concentran la mayor parte del volumen.",
    impact: "Los usuarios analiticos dependen de capas curadas incompletas.",
    actionType: "configuration",
  },
  {
    id: "rec-controltower",
    sourceId: "controltower_postgres",
    severity: "medium",
    category: "Foundation",
    title: "Base interna Control Tower pendiente de snapshots reales",
    recommendation: "Crear contenedor controltower_postgres, aplicar DDL y activar refresh periodico.",
    evidence: "Tablas internas definidas, pero historico aun pendiente.",
    impact: "Sin snapshots no hay evolucion historica ni alertas persistentes.",
    actionType: "configuration",
  },
];

export const implementationPhases: ImplementationPhase[] = [
  { phase: "Fase 0", title: "Preparacion", status: "ready", outcome: "Validar Docker, conexiones y secretos sin passwords en codigo." },
  { phase: "Fase 1", title: "Base interna", status: "next", outcome: "Crear controltower_postgres, DDL y seeds de fuentes." },
  { phase: "Fase 2", title: "Backend PostgreSQL", status: "planned", outcome: "Adapters, health checks, metricas, sesiones, locks e inventario." },
  { phase: "Fase 3", title: "Azure PostgreSQL", status: "planned", outcome: "Conexion SSL, metricas SQL y Azure Monitor." },
  { phase: "Fase 4", title: "Frontend Overview", status: "ready", outcome: "Cards, health score, badges y detalle visual." },
  { phase: "Fase 5", title: "Inventario y detalle", status: "ready", outcome: "Tablas, schemas, tamanos, sesiones y snapshots." },
  { phase: "Fase 6-10", title: "Cloud y Databricks", status: "planned", outcome: "Key Vault, App Insights, Log Analytics, Azure Monitor y Lakehouse." },
  { phase: "Fase 11-12", title: "Copilot y demo final", status: "planned", outcome: "Reglas DBA, recomendaciones y flujo final de presentacion." },
];

export function sourceById(id: string) {
  return databaseSources.find((source) => source.id === id) ?? databaseSources[0];
}

export function formatPort(port: number | null) {
  return port ? `${port}` : "managed";
}

export function formatSize(value: number | null) {
  if (value === null) return "Lakehouse";
  if (value >= 1024) return `${(value / 1024).toFixed(1)} GB`;
  return `${value} MB`;
}

export function sourceIcon(source: DatabaseSource) {
  if (source.sourceType === "lakehouse") return Sparkles;
  if (source.cloudProvider === "azure") return Cloud;
  if (source.sourceType === "system_database") return ShieldCheck;
  return Database;
}
